const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.DragnDrop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Json.Exps.Get,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{fullScreenBtn: 0},
	{shareBtn: 0},
	{audioBtn: 0},
	{refreshBtn: 0},
	{isActive: 0},
	{prevBtn: 0},
	{nextBtn: 0},
	{solbar: 0},
	{polarJSON: 0},
	{AJAX: 0},
	{randomArray: 0},
	{Browser: 0},
	{orbitalLogo: 0},
	{Touch: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{molekul1: 0},
	{molekul2: 0},
	{molekul3: 0},
	{molekul4: 0},
	{molekul5: 0},
	{molekul6: 0},
	{molekul7: 0},
	{molekul8: 0},
	{molekul9: 0},
	{molekul10: 0},
	{molekul11: 0},
	{molekul12: 0},
	{molekul13: 0},
	{molekul14: 0},
	{molekul15: 0},
	{molekul16: 0},
	{molekul17: 0},
	{molekul18: 0},
	{molekul19: 0},
	{molekul20: 0},
	{molekul21: 0},
	{elekNegTitle: 0},
	{elekNegText1: 0},
	{elekNegText2: 0},
	{yükdağilim: 0},
	{momentum: 0},
	{polarlik: 0},
	{val: 0},
	{dengeli: 0},
	{dengesiz: 0},
	{polar: 0},
	{apolar: 0},
	{dipol: 0},
	{dipolZero: 0},
	{posX: 0},
	{posY: 0},
	{snegatif: 0},
	{spozitif: 0},
	{molekul0: 0},
	{completed: 0},
	{yükparça: 0},
	{yükparça2: 0},
	{molekul22: 0},
	{Audio: 0},
	{molekuller: 0},
	{answerBtn: 0},
	{yukparca: 0},
	{DragDrop: 0},
	{sBtn: 0},
	{dipolBtn: 0},
	{yukDagilimBtn: 0},
	{polarBtn: 0},
	{molekulPosX: 0},
	{molekulPosY: 0},
	{yukDagilimControl: 0},
	{polarControl: 0},
	{dipolControl: 0},
	{answerUID: 0},
	{yukParcaControl: 0},
	{sVal: 0},
	{isLoader: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	prevBtn: class extends self.ISpriteInstance {},
	nextBtn: class extends self.ISpriteInstance {},
	solbar: class extends self.ISpriteInstance {},
	polarJSON: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	randomArray: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	orbitalLogo: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	molekul1: class extends self.ISpriteInstance {},
	molekul2: class extends self.ISpriteInstance {},
	molekul3: class extends self.ISpriteInstance {},
	molekul4: class extends self.ISpriteInstance {},
	molekul5: class extends self.ISpriteInstance {},
	molekul6: class extends self.ISpriteInstance {},
	molekul7: class extends self.ISpriteInstance {},
	molekul8: class extends self.ISpriteInstance {},
	molekul9: class extends self.ISpriteInstance {},
	molekul10: class extends self.ISpriteInstance {},
	molekul11: class extends self.ISpriteInstance {},
	molekul12: class extends self.ISpriteInstance {},
	molekul13: class extends self.ISpriteInstance {},
	molekul14: class extends self.ISpriteInstance {},
	molekul15: class extends self.ISpriteInstance {},
	molekul16: class extends self.ISpriteInstance {},
	molekul17: class extends self.ISpriteInstance {},
	molekul18: class extends self.ISpriteInstance {},
	molekul19: class extends self.ISpriteInstance {},
	molekul20: class extends self.ISpriteInstance {},
	molekul21: class extends self.ISpriteInstance {},
	elekNegTitle: class extends self.ITextInstance {},
	elekNegText1: class extends self.ITextInstance {},
	elekNegText2: class extends self.ITextInstance {},
	yükdağilim: class extends self.ISpriteInstance {},
	momentum: class extends self.ISpriteInstance {},
	polarlik: class extends self.ISpriteInstance {},
	dengeli: class extends self.ISpriteInstance {},
	dengesiz: class extends self.ISpriteInstance {},
	polar: class extends self.ISpriteInstance {},
	apolar: class extends self.ISpriteInstance {},
	dipol: class extends self.ISpriteInstance {},
	dipolZero: class extends self.ISpriteInstance {},
	snegatif: class extends self.ISpriteInstance {},
	spozitif: class extends self.ISpriteInstance {},
	molekul0: class extends self.ISpriteInstance {},
	yükparça: class extends self.ISpriteInstance {},
	yükparça2: class extends self.ISpriteInstance {},
	molekul22: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	molekuller: class extends self.ISpriteInstance {},
	answerBtn: class extends self.ISpriteInstance {},
	yukparca: class extends self.ISpriteInstance {},
	sBtn: class extends self.ISpriteInstance {},
	dipolBtn: class extends self.ISpriteInstance {},
	yukDagilimBtn: class extends self.ISpriteInstance {},
	polarBtn: class extends self.ISpriteInstance {}
}